2021-04-22 06:30:22.558482: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory

2021-04-22 06:30:22.558533: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

2021-04-22 06:30:23.608495: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set

2021-04-22 06:30:23.608663: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory

2021-04-22 06:30:23.608704: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)

2021-04-22 06:30:23.608738: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (8796370f0e35): /proc/driver/nvidia/version does not exist

2021-04-22 06:30:23.608897: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 FMA

To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

2021-04-22 06:30:23.609034: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set

Form data requires "python-multipart" to be installed.

You can install "python-multipart" with:


pip install python-multipart


Traceback (most recent call last):

File "/usr/local/lib/python3.6/dist-packages/fastapi/dependencies/utils.py", line 93, in check_file_field

from multipart import __version__ # type: ignore

ModuleNotFoundError: No module named 'multipart'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/usr/local/bin/uvicorn", line 8, in <module>

sys.exit(main())

File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__

return self.main(*args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main

rv = self.invoke(ctx)

File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke

return ctx.invoke(self.callback, **ctx.params)

File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke

return callback(*args, **kwargs)

File "/usr/local/lib/python3.6/dist-packages/uvicorn/main.py", line 362, in main

run(**kwargs)

File "/usr/local/lib/python3.6/dist-packages/uvicorn/main.py", line 386, in run

server.run()

File "/usr/local/lib/python3.6/dist-packages/uvicorn/server.py", line 49, in run

loop.run_until_complete(self.serve(sockets=sockets))

File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete

return future.result()

File "/usr/local/lib/python3.6/dist-packages/uvicorn/server.py", line 56, in serve

config.load()

File "/usr/local/lib/python3.6/dist-packages/uvicorn/config.py", line 308, in load

self.loaded_app = import_from_string(self.app)

File "/usr/local/lib/python3.6/dist-packages/uvicorn/importer.py", line 20, in import_from_string

module = importlib.import_module(module_str)

File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 994, in _gcd_import

File "<frozen importlib._bootstrap>", line 971, in _find_and_load

File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 665, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 678, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "./app/main.py", line 88, in <module>

async def create_upload_file(file: UploadFile = File(...)):

File "/usr/local/lib/python3.6/dist-packages/fastapi/routing.py", line 574, in decorator

callbacks=callbacks,

File "/usr/local/lib/python3.6/dist-packages/fastapi/routing.py", line 520, in add_api_route

callbacks=current_callbacks,

File "/usr/local/lib/python3.6/dist-packages/fastapi/routing.py", line 386, in __init__

self.body_field = get_body_field(dependant=self.dependant, name=self.unique_id)

File "/usr/local/lib/python3.6/dist-packages/fastapi/dependencies/utils.py", line 782, in get_body_field

check_file_field(final_field)

File "/usr/local/lib/python3.6/dist-packages/fastapi/dependencies/utils.py", line 106, in check_file_field

raise RuntimeError(multipart_not_installed_error)

RuntimeError: Form data requires "python-multipart" to be installed.

You can install "python-multipart" with:


pip install python-multipart